### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by simov** [martinheidegger/qs-iconv#1]
Hi @martinheidegger,

Can you remove request from the dependencies list?

Also the iconv peer dependency is being installed when using NPM2. In your docs it is mentioned that the user should install it separately, so I don't see a problem removing it from package.json

**Comment by martinheidegger** [comment]
Thank you for checking out the repo and the code.

I moved request from the `dependencies` to the `devDependencies` _(where it belongs)_ and also removed the `iconv` dependency as you recommended _(Thanks!)_. It is pushed as https://github.com/martinheidegger/qs-iconv/commit/1aabe1cc49ece734f6947f2f22cd960dcbd11eb1 and published it as `1.0.3`

**Comment by simov** [comment]
Thanks! I think I'm going to add your request example somewhere in the request docs, and close a few issues with it.
