### ISSUE TITLE
encoder produces incorrectly encoded string when there are characters from 0x00-0x10 range.

### ISSUE THREAD

**Issue by atteheino** [martinheidegger/qs-iconv#2]
Hi @martinheidegger !

There is issue where encoder produces incorrectly encoded string when there are characters from 0x00-0x10 range. For example NEW LINE \n got encoded to %A that is not accepted by all decoders. (%0A is the correct form)

To fix this I created this hack to encoder.js:

```JavaScript
-  return '%' + char.toString(16).toUpperCase()
+  // pad hex 0x00 to 0x10 with 0 to comply with standard notation
+  if (char < 0x10) {
+    return '%0' + char.toString(16).toUpperCase()
+  } else {
+    return '%' + char.toString(16).toUpperCase()
+  }
```

I also added a test case to test/encoder.js:

```JavaScript
test('Encoder correctly handles short characters like linefeed', function (t) {
  t.equal(qs.stringify({
    test: 'test\r\ntest'
  }, {
    encoder: qsIconv.encoder('ISO-8859-1')
  }), 'test=test%0D%0Atest')
  t.end()
})
```

**Comment by martinheidegger** [comment]
Hello @atteheino !

Thank you for your input. I took your suggestion and pushed a fix that contains your code! It is now deployed as `1.0.4`. It took a little because a web service that I relied to for the tests was shut down. Sorry for the delay.

**Comment by atteheino** [comment]
Thanks!

Atte

30.11.2016 3.52 "Martin Heidegger" <notifications@github.com> kirjoitti:
